version: '3.7'

services:
    frontend:
        image: product-similarity-frontend:1
        build:
            context: ./
            dockerfile: frontend/Dockerfile
        ports:
            - '3000:3000'
        command: npm run start
        restart: on-failure

    backend:
        image: product-similarity-backend:1
        build:
            context: ./
            dockerfile: backend/Dockerfile
        ports:
            - '5000:5000'
        command: gunicorn --bind 0.0.0.0:5000 flask_server:app
        env_file:
            - backend/.env.prod
        restart: on-failure
